spring:
  application:
    name: calendar
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://production.yml:5432/smart-calendar
    username: postgres
    password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none