spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: calendar
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/smart-calendar
    username: postgres
    password: 123
  liquibase:
    enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  config: classpath:logback-colored.xml